[project]
name = "clanker"
version = "0.1.0"
description = "An LLM app environment."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marvin",
    "typer",
    "rich",
    "pydantic",
    "pydantic-ai",
    "pyyaml",
]

[tool.uv.workspace]
members = ["apps/*"]

[tool.uv.sources]
clanker = { path = "src/clanker", editable = true }
