[project]
name = "recipes"
version = "0.1.0"
description = "Simple recipe manager"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clanker",
    "pydantic",
    "rich",
    "python-frontmatter",
    "pydantic-ai",
]

[tool.uv.sources]
clanker = { path = "../../", editable = true }
