[project]
name = "example"
version = "0.1.0"
description = "Example app demonstrating export-based Clanker integration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clanker",
]

[tool.uv.sources]
clanker = { path = "../../", editable = true }
