[project]
name = "clanker"
version = "0.1.0"
description = "The clanker."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "pydantic-ai",
  "python-dotenv",
  "pyyaml",
  "marvin",
  "loguru",
]
