[project]
name = "scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clanker",
    "marvin>=3.2.0",
]

[tool.uv.sources]
clanker = { path = "../", editable = true }
